# Generated by Django 4.1.4 on 2023-01-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_snippet_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='grade',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SE', 'Senior')], max_length=20),
        ),
    ]
