# Generated by Django 4.1.4 on 2023-01-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_snippet_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='grade',
        ),
        migrations.AddField(
            model_name='snippet',
            name='FR',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='snippet',
            name='JR',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='snippet',
            name='SE',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='snippet',
            name='SO',
            field=models.BooleanField(default=False),
        ),
    ]
