# Generated by Django 4.1.4 on 2023-01-18 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_snippet_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='email',
            field=models.EmailField(default=False, max_length=254),
        ),
        migrations.AddField(
            model_name='snippet',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
