# Generated by Django 4.1.4 on 2023-01-18 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_snippet_email_snippet_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
