# Generated by Django 4.1.4 on 2023-01-30 20:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_alter_snippet_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='event',
            field=models.CharField(choices=[('Boys Basketball', 'Boys Basketball'), ('Girls Basketball', 'Girls Basketball'), ('Sweet Heart Pep Rally', 'Sweet Heart Pep Rally'), ('Other', 'Other')], default='Other', max_length=25),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 30, 20, 43, 10, 200868, tzinfo=datetime.timezone.utc)),
        ),
    ]
