# Generated by Django 4.1.4 on 2023-01-31 19:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_option_rename_se_snippet_sr_remove_snippet_event_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='option',
            new_name='event',
        ),
        migrations.AlterField(
            model_name='snippet',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 31, 19, 13, 0, 62594, tzinfo=datetime.timezone.utc)),
        ),
    ]
