# Generated by Django 4.1.4 on 2023-01-31 19:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_rename_option_snippet_event_alter_snippet_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Option',
            new_name='Events',
        ),
        migrations.AlterField(
            model_name='snippet',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 31, 19, 19, 33, 659074, tzinfo=datetime.timezone.utc)),
        ),
    ]
