# Generated by Django 4.1.4 on 2023-01-31 19:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_rename_option_events_alter_snippet_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
        migrations.AlterField(
            model_name='snippet',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 31, 19, 21, 26, 318835, tzinfo=datetime.timezone.utc)),
        ),
    ]
