# Generated by Django 4.1.4 on 2023-03-30 02:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_rename_events_event_alter_snippet_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 30, 2, 48, 49, 916091, tzinfo=datetime.timezone.utc)),
        ),
    ]
